# Generated by Django 5.0.3 on 2024-03-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Manufacturers',
            new_name='manufacturer',
        ),
    ]
